apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-store
  namespace: ecommerce
  labels:
    app: ecommerce-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-store
  template:
    metadata:
      labels:
        app: ecommerce-store
    spec:
      containers:
        - name: ecommerce-store
          image: innovacr.azurecr.io/ecommercestore
          ports:
            - containerPort: 3001
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://ecommerce-admin:3000/api/e86373f-8e79-424e-a291-73c20ad18f76"
            - name: REACT_EDITOR
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: REACT-EDITOR
            - name: BILLBOARD_ID
              value: "a67740f1-59db-4e44-a704-9d9b7f68c714"
          volumeMounts:
            - name: secrets-store-inline-store
              mountPath: /mnt/secrets-store/store
              readOnly: true
      volumes:
        - name: secrets-store-inline-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"